[build]
  base = "/"
  command = "ng build"
  publish = "dist/portfolio"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "netlify-plugin-check-output-for-puppy-references"
  [plugins.inputs]
    breeds = ["pomeranian", "chihuahua", "bulldog"]

[build.processing.html]
  pretty_urls = true
